# The name given to the Headless Chrome service (lowercase alphanumeric only).
chrome-headless:
    # The type of your service (chrome-headless), which uses the format
    # 'type:version'. Be sure to consult the Headless Chrome documentation
    # (https://docs.platform.sh/add-services/headless-chrome.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: chrome-headless:120

# The name given to the Network Storage service (lowercase alphanumeric only).
network-storage:
    # The type of your service (network-storage), which uses the format
    # 'type:version'. Be sure to consult the Network Storage documentation
    # (https://docs.platform.sh/add-services/network-storage.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: network-storage:2.0
    # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
    disk: 256

# The name given to the OpenSearch service (lowercase alphanumeric only).
opensearch:
    # The type of your service (opensearch), which uses the format
    # 'type:version'. Be sure to consult the OpenSearch documentation
    # (https://docs.platform.sh/add-services/opensearch.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: opensearch:2
    # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
    disk: 256

# The name given to the Oracle MySQL service (lowercase alphanumeric only).
oracle-mysql:
    # The type of your service (oracle-mysql), which uses the format
    # 'type:version'. Be sure to consult the Oracle MySQL documentation
    # (https://docs.platform.sh/add-services/mysql.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: oracle-mysql:8.0
    # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
    disk: 256

# The name given to the PostgreSQL service (lowercase alphanumeric only).
postgresql:
    # The type of your service (postgresql), which uses the format
    # 'type:version'. Be sure to consult the PostgreSQL documentation
    # (https://docs.platform.sh/add-services/postgresql.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: postgresql:17
    # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
    disk: 256

